# Generated by Django 4.0.5 on 2022-06-25 21:18

import comu.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('permission', models.PositiveSmallIntegerField()),
                ('filename', models.FileField(upload_to=comu.models.upload_file, validators=[comu.models.validate_size])),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_code', models.CharField(max_length=6)),
                ('create_date', models.DateField(auto_now=True)),
                ('filter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comu.filter')),
            ],
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('filter_id', 'stock_code', 'create_date'), name='unique_reporting'),
        ),
    ]
