# Generated by Django 4.0.5 on 2022-06-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
