# Generated by Django 4.0.5 on 2022-06-25 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comu', '0002_alter_filter_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
    ]
