# Generated by Django 4.0.5 on 2022-06-25 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comu', '0003_alter_filter_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='filter_id',
            new_name='filter',
        ),
        migrations.AlterField(
            model_name='filter',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AlterField(
            model_name='filter',
            name='permission',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
